### ISSUE TITLE
Worlds with custom blocks cannot be imported to Minecraft

### ISSUE THREAD

**Issue by PRO100KatYT** [bedrock-tool/bedrocktool#35]
![ss](https://user-images.githubusercontent.com/67335438/214785940-40a7d746-c1f4-4b6a-913f-617a52b4200f.png)

The world save from a server with custom blocks lacks the levelname.txt file and the level.dat file seems to be empty.
Worlds without custom blocks seem to be fine.
Tested on the latest version from releases.

**Comment by olebeck** [comment]
Hm that's a weird bug, are there any errors logged in the program?
Also do note that custom blocks are still breaking the block palette in worlds above 1.18 due to a bug in the decoding

**Comment by PRO100KatYT** [comment]
When saving the world there is an "Process can't access the file because it is being used by another process" error for the world\db\LOCK file.
I think it's also worth mentioning that on the version prior to [this commit](https://github.com/bedrock-tool/bedrocktool/commit/a4a293ef5209df00b209f21ebe9ecf2a223f8e79) the same world was saved correctly for me.

**Comment by olebeck** [comment]
yes thats completely right, in that commit i made it set experiments to on by default if the world uses a behavior pack.
its implemented wrong and should be bool not int like that its making invalid nbt and therefore errors saving the level.dat.
fixed in most recent commit, not tested that custom blocks work above 1.17 yet however it shouldnt break worlds now
