### ISSUE TITLE
CubeCraft Archiving is now worse.

### ISSUE THREAD

**Issue by StrafeYourself** [bedrock-tool/bedrocktool#55]
Hey, Obebeck,
Thank you so much for trying to fix the CubeCraft Archiving issue. However, instead of fixing it is somehow gotten worse then better to the point where all the blocks are completely black and when imported into the game and when loading into the world in crashes before we can even load into it.

**Comment by AhmedSalih122** [comment]
True, also happening to me and it's really annoying, but just a suggestion for the next time reporting a bug, don't address it like a formal letter to someone, list what the bug is in the title and give an in depth description of what the bug is in the post itself instead of using the title like an email header and the report as the email itself.

**Comment by olebeck** [comment]
#54 temporary problem until the 1.19.70 update is implemented correctly

**Comment by StrafeYourself** [comment]
Thank you olebeck great to have you by me side.
